### ISSUE TITLE
Bug: Navigation rendering on Windows and missing profile pic

### ISSUE THREAD

**Issue by x-snackage-x** [ZHAW-PM4-Compass/compass#74]
**Describe the bug**
On Windows navigation is broken because of different slider.  
Profile pic is broken because of CORS maybe?

**To Reproduce**
1. Go to staging on Windows
2. Look at left hand side navigation
3. Look at profile pic

**Desktop**
 - OS: Windows for navigation, all for profile pic

**Comment by noahbaumgartner** [comment]
Bug has been fixed with Pull Request #78
