### ISSUE TITLE
As participant I want to create daily worktime entries

### ISSUE THREAD

**Issue by Tima000h** [ZHAW-PM4-Compass/compass#8]
Further Details
As participant I want to create daily worktime entries. I can edit and delete timestamps.

Estimate
M Storypoints

Tasks Checklist

- [X] Create Dateobjects
- [X] Define theme/look
- [X] Create necessary Controller/Service & Repositories
- [X] Generate OpenApi interface
- [X] Create Tests

Acceptance Criteria
"No-Tech" A participant can create, navigate, edit and delete his worktime.
Presentation looks like a real product.

Dependencies
This user story depends on the project being mature enough to be able to present concrete features.
This user story depends on components

**Comment by brunndar** [comment]
1. API erstellen
2. Implementierung

Bereiche:
- UI
- Backend
- Database

**Comment by Tima000h** [comment]
getDaySheetByDate funktioniert mit Aufrufen vom Frontend nicht. Mit dem Postman funktioniert es jedoch?
@eulus
