### ISSUE TITLE
Initial Data Model

### ISSUE THREAD

**Issue by x-snackage-x** [ZHAW-PM4-Compass/compass#9]
Create a first proposal of the Compass Data Model.

First Group: Authorisation & Roles:
- Authorization, Roles and other access control structures will be handled by an external provider: necessary tables will be defined by @noahbaumgartner 
- Will be condensed as "User" and "Role" for now

Second Group: Event Tracking
- time stamping entries
- special events

Third Group: Reports and Mood
- daily sheet
- mood
- behavior
- report

Model in [Draw IO](
https://drive.google.com/file/d/1HxZfytQRKlVXRHy6lyiiYArwV3BXttqL/view?usp=sharing) (einfach Draw IO in app Drop-down wählen)

**Comment by eulus** [comment]
[Compass Data Model.txt](https://github.com/ZHAW-PM4-Compass/compass/files/14670116/Compass.Data.Model.txt)
einfach endung zu drawio ändern

Categories extended

**Comment by noahbaumgartner** [comment]
@x-snackage-x User ist ergänzt. Vorerst wird nur die User-Id gespeichert, um keine Redundanzen zwischen auth0 und unserer DB zu schaffen.
